# Generated by Django 4.1.4 on 2023-03-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=100, verbose_name='Имя проекта')),
                ('town', models.CharField(max_length=50, verbose_name='Город')),
                ('description', models.TextField(max_length=150, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото')),
                ('urlProject', models.CharField(max_length=200, verbose_name='URL-адрес проекта')),
                ('helper_card', models.CharField(default='НЕ ИСПОЛЬЗУЙТЕ ОГРОМНЫЕ КАРТИНКИ! Ниже кнопка для оптимизации. Далее на ПК откройте картинку -> ПКМ -> изменить размер изображения, выберите между 1 и 2 пунктами.', max_length=500, verbose_name='ПРИМЕЧАНИЕ')),
            ],
        ),
    ]
