# Generated by Django 4.1.4 on 2023-03-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_sale_toolcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('price', models.CharField(default='', max_length=50, verbose_name='Цена')),
                ('description', models.TextField(default='', max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото')),
                ('urlProduct', models.CharField(max_length=200, verbose_name='URL-адрес проекта')),
                ('helper_card', models.CharField(default='НЕ ИСПОЛЬЗУЙТЕ ОГРОМНЫЕ КАРТИНКИ! Ниже кнопка для оптимизации. Далее на ПК откройте картинку -> ПКМ -> изменить размер изображения, выберите между 1 и 2 пунктами.', max_length=500, verbose_name='ПРИМЕЧАНИЕ')),
                ('saletime', models.TextField(default='', max_length=150, verbose_name='Время акции')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecorCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('price', models.CharField(default='', max_length=50, verbose_name='Цена')),
                ('description', models.TextField(default='', max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото')),
                ('urlProduct', models.CharField(max_length=200, verbose_name='URL-адрес проекта')),
                ('helper_card', models.CharField(default='НЕ ИСПОЛЬЗУЙТЕ ОГРОМНЫЕ КАРТИНКИ! Ниже кнопка для оптимизации. Далее на ПК откройте картинку -> ПКМ -> изменить размер изображения, выберите между 1 и 2 пунктами.', max_length=500, verbose_name='ПРИМЕЧАНИЕ')),
                ('saletime', models.TextField(default='', max_length=150, verbose_name='Время акции')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GardenCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('price', models.CharField(default='', max_length=50, verbose_name='Цена')),
                ('description', models.TextField(default='', max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото')),
                ('urlProduct', models.CharField(max_length=200, verbose_name='URL-адрес проекта')),
                ('helper_card', models.CharField(default='НЕ ИСПОЛЬЗУЙТЕ ОГРОМНЫЕ КАРТИНКИ! Ниже кнопка для оптимизации. Далее на ПК откройте картинку -> ПКМ -> изменить размер изображения, выберите между 1 и 2 пунктами.', max_length=500, verbose_name='ПРИМЕЧАНИЕ')),
                ('saletime', models.TextField(default='', max_length=150, verbose_name='Время акции')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('price', models.CharField(default='', max_length=50, verbose_name='Цена')),
                ('description', models.TextField(default='', max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото')),
                ('urlProduct', models.CharField(max_length=200, verbose_name='URL-адрес проекта')),
                ('helper_card', models.CharField(default='НЕ ИСПОЛЬЗУЙТЕ ОГРОМНЫЕ КАРТИНКИ! Ниже кнопка для оптимизации. Далее на ПК откройте картинку -> ПКМ -> изменить размер изображения, выберите между 1 и 2 пунктами.', max_length=500, verbose_name='ПРИМЕЧАНИЕ')),
                ('saletime', models.TextField(default='', max_length=150, verbose_name='Время акции')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
