# Generated by Django 4.1.4 on 2023-03-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_buildcard_decorcard_gardencard_homecard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildcard',
            options={'verbose_name': 'Карточки - Стройматериалы', 'verbose_name_plural': 'Карточки - Стройматериалы'},
        ),
        migrations.AlterModelOptions(
            name='decorcard',
            options={'verbose_name': 'Карточки - Отделочные Материалы', 'verbose_name_plural': 'Карточки - Отделочные Материалы'},
        ),
        migrations.AlterModelOptions(
            name='gardencard',
            options={'verbose_name': 'Карточки - Огород и Сад', 'verbose_name_plural': 'Карточки - Огород и Сад'},
        ),
        migrations.AlterModelOptions(
            name='homecard',
            options={'verbose_name': 'Карточки - Для дома', 'verbose_name_plural': 'Карточки - Для дома'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Странички продуктов', 'verbose_name_plural': 'Странички продуктов'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Карточки - Акции', 'verbose_name_plural': 'Карточки - Акции'},
        ),
        migrations.AlterModelOptions(
            name='toolcard',
            options={'verbose_name': 'Карточки - Инструменты', 'verbose_name_plural': 'Карточки - Инструменты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(default='<p> Абзац </p>\n <ul>\n<li>Пункт</li>\n</ul>\n', help_text='2000 символов.', max_length=2000, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='help_product',
            field=models.CharField(default='Вы можете удалить/добавить любые html-теги.\nтег <p> - абзац, введите между ним текст.\nКонтролируйте ваши тексты как вам удобно, делите абзацы на строки с помощью Enter.тег <ul> - список с точками. Внутри него тег <li>, в него вписывается элемент списка.\nтег <ol> - список с цифрами. Замените <ul> на <ol>.\nПросто скопируйте строку с пунктом <li> и вставьте сколько пунктов вам нужно. Или сделайте несколько списков.\nЕсли вы хотите добавить заголовок - <h2> Заголовок </h2> (от большего (h1) к меньшему (h6).\nНе бойтесь и помните, что вы всегда можете сохранить и посмотреть результат на сайте, а так же макет справа в меню админ. панели "Вакансии"!', max_length=1000, verbose_name='ПРИМЕЧАНИЕ'),
        ),
        migrations.AddField(
            model_name='product',
            name='helper',
            field=models.CharField(default='НЕ ИСПОЛЬЗУЙТЕ ОГРОМНЫЕ КАРТИНКИ! Ниже кнопка для оптимизации. Далее на ПК откройте картинку -> ПКМ -> изменить размер изображения, выберите пункт 3.', max_length=500, verbose_name='ПРИМЕЧАНИЕ'),
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение - 2k. На Vanlaar для 1 фото стоит 2508х1672', upload_to='', verbose_name='Фотокарточка'),
        ),
        migrations.AddField(
            model_name='product',
            name='productName',
            field=models.CharField(default='', help_text='Имя для ссылки. Пример: gvozdi -> получаем: stroyshop.ru/product/gvozdi', max_length=1000, verbose_name='Имя ссылки продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='textOne',
            field=models.TextField(default='<p> Абзац </p>\n', help_text='Текст после первой картинки. Сверху, над именем проекта.', max_length=2000, verbose_name='Доп. текст, 2000 символов.'),
        ),
        migrations.AddField(
            model_name='product',
            name='textTwo',
            field=models.TextField(default='<p> Абзац </p>\n', help_text='Текст после первой картинки. Снизу, под именем проекта.', max_length=2000, verbose_name='Доп. текст, 2000 символов.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='<p> Абзац </p>\n', help_text='3000 символов.', max_length=3000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Имя проекта на самой странице продукта.', max_length=500, verbose_name='Имя проекта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
