# Generated by Django 4.1.4 on 2023-04-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildcard',
            name='image2',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='buildcard',
            name='image3',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='decorcard',
            name='image2',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='decorcard',
            name='image3',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='gardencard',
            name='image2',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='gardencard',
            name='image3',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='homecard',
            name='image2',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='homecard',
            name='image3',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='sale',
            name='image2',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='sale',
            name='image3',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='toolcard',
            name='image2',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='toolcard',
            name='image3',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение до 2k. пр. ~1700х1100, 1448x1448', upload_to='', verbose_name='Фото 3'),
        ),
    ]
