# Generated by Django 4.1.4 on 2023-04-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_buildcard_image2_buildcard_image3_decorcard_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildcard',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='buildcard',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='decorcard',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='decorcard',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='gardencard',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='gardencard',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='homecard',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='homecard',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='toolcard',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='toolcard',
            name='image3',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение - 2k.', upload_to='', verbose_name='Фотокарточка 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение - 2k.', upload_to='', verbose_name='Фотокарточка 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, help_text='Рекомендуемое разрешение - 2k.', upload_to='', verbose_name='Фотокарточка 1'),
        ),
    ]
